### ISSUE TITLE
FileNotFoundError while training the model

### ISSUE THREAD

**Issue by zavorra** [AidaDSP/Automated-GuitarAmpModelling#5]
Sorry for the poor formatting, i am on mobile... I am raising an issue that is often reported in the [Mod Forum](https://forum.mod.audio/t/filenotfounderror-while-training-the-model/9774) 

When training models on the colab notebook, step 3 often (always?) Results in the following error:
<P>
step 3 result

FileNotFoundError Traceback (most recent call last)
in <cell line: 13>()
11
12 model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}"
—> 13 model_path, esr = extract_best_esr_model(model_dir)
14 model_data = miscfuncs.json_load(model_path)
15 model = load_model(model_data).to(device)

/content/Automated-GuitarAmpModelling/colab_functions.py in extract_best_esr_model(dirpath)
91 def extract_best_esr_model(dirpath):
92 stats_file = dirpath + “/training_stats.json”
—> 93 with open(stats_file) as json_file:
94 stats_data = json.load(json_file)
95 test_lossESR_final = stats_data[‘test_lossESR_final’]

FileNotFoundError: [Errno 2] No such file or directory: ‘/content/Automated-GuitarAmpModelling/Results/aida_LSTM-16/training_stats.json’
</p>

...

I have noticed that could be related to the following different definitions:

in step 2

model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}-{skip_con}"

Where skip_con can be 0 or 1

While in step 3

model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}"

**Comment by MaxPayne86** [comment]
Should have been fixed by a75599006b18cdef10459cfb755788527f4c5406, re-open otherwise
