### ISSUE TITLE
Trainer expects a different directory name in steps 3 and 4

### ISSUE THREAD

**Issue by avanzzzi** [AidaDSP/Automated-GuitarAmpModelling#6]
In the trainer, avaiable at: https://colab.research.google.com/drive/1n3EOnroDSGoj_8PVRP6UEwUXUzPewv8p

The steps 3. Model Evaluation and 4. Model Export expects a directory name with the format:

`.../Results/f'{args.file_name}_{args.unit_type}-{args.hidden_size}'`
for example: `.../Results/JCA SLO Mod_LSTM-16`

That doesn't exists. The actual directory is being created with a suffix "-0" 
Probably related to the current execution version. In my case: `.../Results/JCA SLO Mod_LSTM-16-0` .

Removing the "-0" suffix allows the steps 3 and 4 to pass.

**Comment by avanzzzi** [comment]
After a second look, It's related to the `skip_con` parameter.

```model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}-{skip_con}"```

So that suffix will always be there, as `0` or `1`

**Comment by MaxPayne86** [comment]
Should be closed by a75599006b18cdef10459cfb755788527f4c5406, re-open otherwise
